# Generated by Django 5.2.7 on 2025-11-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerroadmap',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
