# Generated by Django 5.2.7 on 2025-11-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_careerroadmap_preferences_careerroadmap_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerroadmap',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='career.careerroadmap'),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roadmapreference',
            name='auto_refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
